### ISSUE TITLE
Dew Point

### ISSUE THREAD

**Issue by ghost** [ayeks/bme680_to_influxdb#9]
No issue just a noob here trying to get dew point calculation to work. Any help is welcome Thanks.

**Comment by ayeks** [comment]
Hey @Commander-Crash,

before dealing with mold in my bedroom I also had no idea about the dew point. Checkout this [simple calculator](https://www.calculator.net/dew-point-calculator.html) and this [example calculation](https://www.learntocalculate.com/calculate-dew-point/).

> Dew point is defined as the temperature at which a given volume of air at a certain atmospheric pressure is saturated with water vapor, causing condensation and the formation of dew. Dew is the condensed water that a person often sees on flowers and grass early in the morning. Dew point varies depending on the amount of water vapor present in the air, with more humid air resulting in a higher dew point than dry air. Furthermore, the higher the relative humidity, the closer the dew point to the current air temperature, with 100% relative humidity meaning that dew point is equivalent to the current temperature. In cases where dew point is below freezing (0°C or 32°F), the water vapor turns directly into frost rather than dew.

For example having 20°C air temperature in the room and a 65% relative humidity - the calculated due point is 13.2°C.
When you have blank stone walls without insulation, like me, you have the problem that these walls are colder than 13.2°C in winter. That means that the water in the air will become liquid on these walls (my walls are sometimes at only 10°C in winter..). Because mold loves dew on cold walls I started to monitor the humidity in the rooms.

In my case I had to buy an air dehumidifier that I leave running half the day when I am not in the room. This device get the humidity down to 45-50%. In consequence there is no dew on the walls and the bedroom is mold free. \o/

Thanks to cheap houses that where build in the 1970th..

Best regards
Lars
